name: Build native library for Windows

on:
  workflow_dispatch:

jobs:
  build:
    name: Build native library for Windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build native library with cargo
        working-directory: natives
        run: cargo build --release
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: soundplayer.dll
          path: natives/target/release/soundplayer.dll
