name: Build native library for Windows

on:
  push:
    tags:
      - "natives-*"

jobs:
  build:
    name: Build native library for Windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build native library with cargo
        working-directory: natives
        run: cargo build --release
      - name: Publish native library to release
        uses: softprops/action-gh-release@v2
        with:
          files: natives/target/release/soundplayer.dll
