name: Build native library for macOS

on:
  push:
    tags:
      - "natives-*"

permissions:
  contents: write

jobs:
  build:
    name: Build native library for macOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache
        uses: actions/cache@v4
        with:
          path: natives/target
          key: ${{runner.os}}-cargo-${{hashFiles('natives/Cargo.lock')}}
      - name: Build native library with cargo
        working-directory: natives
        run: cargo build --release
      - name: Publish native library to release
        uses: softprops/action-gh-release@v2
        with:
          files: natives/target/release/libsoundplayer.dylib
