name: Build native library for Linux

on:
  push:
    tags:
      - "natives-*"

permissions:
  contents: write

jobs:
  build:
    name: Build native library for Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install libasound2-dev
        run: sudo apt install libasound2-dev
      - name: Build native library with cargo
        working-directory: natives
        run: cargo build --release
      - name: Publish native library to release
        uses: softprops/action-gh-release@v2
        with:
          files: natives/target/release/libsoundplayer.so
