name: Build native library for Linux

on:
  workflow_dispatch:

jobs:
  build:
    name: Build native library for Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build native library with cargo
        working-directory: natives
        run: cargo build --release
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: libsoundplayer.so
          path: natives/target/release/libsoundplayer.so
