name: Deploy artifacts to Maven Central when pushed to the main branch

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "natives/**"
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/deploy-artifacts.yml
    secrets:
      centralUsername: ${{secrets.CENTRAL_USERNAME}}
      centralPassword: ${{secrets.CENTRAL_PASSWORD}}
      gpgPrivateKey: ${{secrets.GPG_PRIVATE_KEY}}
      gpgPassphrase: ${{secrets.GPG_PASSPHRASE}}
